python finetune.py \
    --base_model 'decapoda-research/llama-7b-hf' \
    --data_path '/code/alpaca-lora-main/dataset/CSN_python_func_code_string.json' \
    --output_dir './lora-csn_python' \
    --batch_size 150 \
    --micro_batch_size 50 \
    --num_epochs 3 \
    --learning_rate 1e-3 \
    --cutoff_len 512 \
    --val_set_size 2000 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[q_proj,v_proj]' \
    --train_on_inputs \
    --group_by_length